plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

collections:
  resumenes:
    output: true
    permalink: /resumenes/:path

include:
  - /resumenes/resumen.md
  - /resumenes/clase_1.md

theme: jekyll-theme-minimal