// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsbS8Tk9K03wuNqcSE_TnmXKqGT3CYEEo',
    appId: '1:184584972042:web:1e392fe1c7ee8d65fbfcf3',
    messagingSenderId: '184584972042',
    projectId: 'ser-manos-2c2023',
    authDomain: 'ser-manos-2c2023.firebaseapp.com',
    storageBucket: 'ser-manos-2c2023.appspot.com',
    measurementId: 'G-MSXYT25GTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcuhaPQo0HnviC9Iw8DX1jzqCtX9eCK6Y',
    appId: '1:184584972042:android:9f3aa959fd54324afbfcf3',
    messagingSenderId: '184584972042',
    projectId: 'ser-manos-2c2023',
    storageBucket: 'ser-manos-2c2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBadR3_kE5EQcKvWte53BEwICKXztE5K70',
    appId: '1:184584972042:ios:f333c04d459e2d3ffbfcf3',
    messagingSenderId: '184584972042',
    projectId: 'ser-manos-2c2023',
    storageBucket: 'ser-manos-2c2023.appspot.com',
    iosBundleId: 'com.example.multiTp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBadR3_kE5EQcKvWte53BEwICKXztE5K70',
    appId: '1:184584972042:ios:c3c4724994c4a995fbfcf3',
    messagingSenderId: '184584972042',
    projectId: 'ser-manos-2c2023',
    storageBucket: 'ser-manos-2c2023.appspot.com',
    iosBundleId: 'com.example.multiTp.RunnerTests',
  );
}
